import { Octokit } from '@octokit/rest'

const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN })
const OWNER = process.env.GITHUB_OWNER || ''
const REPO = process.env.GITHUB_REPO || ''
const BASE_PATH = process.env.GITHUB_BASE_PATH || 'frontend' // subfolder in the repo

export async function readGitHubFile(path: string): Promise<string | null> {
  try {
    const { data } = await octokit.repos.getContent({ owner: OWNER, repo: REPO, path })
    if ('content' in data && data.content) {
      return Buffer.from(data.content, 'base64').toString('utf-8')
    }
    return null
  } catch {
    return null
  }
}

export async function listGitHubDir(path: string): Promise<string[]> {
  try {
    const { data } = await octokit.repos.getContent({ owner: OWNER, repo: REPO, path })
    if (Array.isArray(data)) {
      return data.map((f) => f.path)
    }
    return []
  } catch {
    return []
  }
}

export async function executeReadPrompt() {
  const content = await readGitHubFile(`${BASE_PATH}/prompts/system-prompt.txt`)
  if (!content) return { error: 'Could not read system-prompt.txt from repo' }
  return { content }
}

export async function executeReadEvals() {
  const files = await listGitHubDir(`${BASE_PATH}/evals`)
  if (files.length === 0) return { evals: [], count: 0 }

  const evals = []
  for (const filePath of files) {
    if (!filePath.endsWith('.json')) continue
    const content = await readGitHubFile(filePath)
    if (content) {
      try {
        evals.push(JSON.parse(content))
      } catch {
        evals.push({ file: filePath, error: 'Invalid JSON' })
      }
    }
  }
  return { evals, count: evals.length }
}

export async function executeCreatePR(args: {
  title: string
  prompt_addition: string
  safety_rule_json: string
}) {
  if (!process.env.GITHUB_TOKEN) {
    return { error: 'GITHUB_TOKEN not configured', pr_url: null }
  }

  try {
    // 1. Get the default branch SHA
    const { data: ref } = await octokit.git.getRef({ owner: OWNER, repo: REPO, ref: 'heads/main' })
    const baseSha = ref.object.sha

    // 2. Create a new branch
    const branchName = `autoval/fix-${Date.now()}`
    await octokit.git.createRef({
      owner: OWNER, repo: REPO,
      ref: `refs/heads/${branchName}`,
      sha: baseSha,
    })

    // 3. Read current prompt
    const currentPrompt = await readGitHubFile(`${BASE_PATH}/prompts/system-prompt.txt`)
    const updatedPrompt = (currentPrompt || '') + '\n\n' + args.prompt_addition

    // 4. Commit updated prompt
    await createOrUpdateFile(
      `${BASE_PATH}/prompts/system-prompt.txt`,
      updatedPrompt,
      `fix: add safety rule - ${args.title}`,
      branchName,
    )

    // 5. Commit new eval file
    const rule = JSON.parse(args.safety_rule_json)
    const evalFileName = (rule.name || 'rule').toLowerCase().replace(/[^a-z0-9]+/g, '-')
    await createOrUpdateFile(
      `${BASE_PATH}/evals/${evalFileName}.json`,
      JSON.stringify(rule, null, 2),
      `test: add safety rule - ${evalFileName}`,
      branchName,
    )

    // 6. Open PR
    const { data: pr } = await octokit.pulls.create({
      owner: OWNER, repo: REPO,
      title: args.title,
      head: branchName,
      base: 'main',
      body: [
        '## Autoval Auto-Fix',
        '',
        '**What changed:**',
        `- Updated system prompt with safety rule`,
        `- Added eval: \`${evalFileName}.json\``,
        '',
        '**Prompt addition:**',
        '```',
        args.prompt_addition,
        '```',
        '',
        '*Generated by Autoval eval agent*',
      ].join('\n'),
    })

    return { pr_url: pr.html_url, status: 'created', branch: branchName }
  } catch (e) {
    const msg = e instanceof Error ? e.message : 'Unknown error'
    console.error('[createPR] Error:', msg)
    return { error: `Failed to create PR: ${msg}`, pr_url: null }
  }
}

async function createOrUpdateFile(
  path: string,
  content: string,
  message: string,
  branch: string,
) {
  // Check if file exists to get its SHA
  let sha: string | undefined
  try {
    const { data } = await octokit.repos.getContent({ owner: OWNER, repo: REPO, path, ref: branch })
    if ('sha' in data) sha = data.sha
  } catch {
    // File doesn't exist yet, that's fine
  }

  await octokit.repos.createOrUpdateFileContents({
    owner: OWNER, repo: REPO, path, message, branch,
    content: Buffer.from(content).toString('base64'),
    ...(sha ? { sha } : {}),
  })
}
